// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop/index.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable/index.vue')['default']
    'Breadcrumb.vue': typeof import('./src/components/Breadcrumb.vue/index.vue')['default']
    Crumbs: typeof import('./src/components/Crumbs/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MenuBox: typeof import('./src/components/MenuBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select/index.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    TimeDate: typeof import('./src/components/TimeDate/index.vue')['default']
  }
}

export {}
